//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modeles.Modele
{
    using System;
    using System.Collections.Generic;
    using Modeles.Commun.BusinessObject;

    public partial class Ordre : BO
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Intensite { get; set; }
        public Nullable<int> Lait { get; set; }
        public Nullable<int> Sucre { get; set; }
        public Nullable<int> Mug { get; set; }
        public string Matricule { get; set; }
    }
}
